# Site settings
title: "Neill Robson's Website"
author: "Neill Robson"
description: >
  The blog and portfolio of a software developer.

url: "https://neillrobson.com"
permalink: /blog/:year/:month/:day/:title/
google-analytics: UA-97090131-1
disqus-shortname: neillrobson
repository: neillrobson/neillrobson.github.io

source: src

# See _plugins
markdown: NeillKramdown

pagination:
  enabled: true
  per_page: 2
  sort_reverse: true

tag_page_layout: tag_page
tag_page_dir: tag

collections:
  projects:
    output: true
    permalink: /:collection/:title/

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - gulpfile.esm.js
  - vendor

keep_files:
  - assets

excerpt_separator: <!--more-->
page_excerpts: true
